---
url: http://ruby.github.io
baseurl: "/rubyspec.github.io"
safe: true
lsi: false
permalink: pretty
source: .
destination: ./public
exclude:
  - Rakefile
  - README.md
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - ./public
  - ./stylesheets/*.scss
markdown: rdiscount
pygments: true
port: 9876
